{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-ffmpeg",
    "version": "1.11.0-dmt",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-dmt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.0-dmt.aar",
          "url": "media3-decoder-ffmpeg-1.11.0-dmt.aar",
          "size": 4311742,
          "sha512": "73c1ae1300ee5b9419c2e0de2ff6f072c79c170a461743e5d11a39a6732fcabe941b4612b969c82c7e16dd9b52a3461a2b0cf723f571fdfb32816025e68a495a",
          "sha256": "54b0aab65a2bb5bb8382fe2eaeed5e42be6d4517f03d7a01203f458f461887c9",
          "sha1": "be175f6416e6024ea04bb3ea1757d174dd1e6ba8",
          "md5": "dadf910dcfccdb4c488a0ee0936ef6de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-dmt"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-dmt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.0-dmt.aar",
          "url": "media3-decoder-ffmpeg-1.11.0-dmt.aar",
          "size": 4311742,
          "sha512": "73c1ae1300ee5b9419c2e0de2ff6f072c79c170a461743e5d11a39a6732fcabe941b4612b969c82c7e16dd9b52a3461a2b0cf723f571fdfb32816025e68a495a",
          "sha256": "54b0aab65a2bb5bb8382fe2eaeed5e42be6d4517f03d7a01203f458f461887c9",
          "sha1": "be175f6416e6024ea04bb3ea1757d174dd1e6ba8",
          "md5": "dadf910dcfccdb4c488a0ee0936ef6de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.0-dmt-sources.jar",
          "url": "media3-decoder-ffmpeg-1.11.0-dmt-sources.jar",
          "size": 12471,
          "sha512": "6c3c0cc3d0c3266a00a5d185363058aea9f72843b2d76d0bb864b6dac02e0394244777a61c49dc3ef5c5de1eaaaf13846e7b2c19e2b1a9ba50ff6b9d8163f15c",
          "sha256": "52d15e6ca890077fc0a670d2b0ff37eec794661181612932ca2f0ec744c6e6ce",
          "sha1": "708d121996793a75da4e6775c3d589917eb6c34f",
          "md5": "baa934257a446ea396c29a90cfd5dd26"
        }
      ]
    }
  ]
}
