{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-common",
    "version": "1.11.0-rc01-dmt",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.11.0-rc01-dmt.aar",
          "url": "media3-common-1.11.0-rc01-dmt.aar",
          "size": 643480,
          "sha512": "a8b73acc52c69ce50a1b8cf05836e2ba5c2199e8ade2dfdc14bd91368cc1cd7b7b6061ff80cee2e0e09dd79b8ffbaee2ec718380bb0bf03d054de18ff059965a",
          "sha256": "2b19297e4dfd101b295ad4c6022c4b257f1bf9560ff6fc23f026824192418fb1",
          "sha1": "8bf30f43e3c07f249e8a52c632a3dbe8f63f05e3",
          "md5": "fcc8a8ee66024c16f0c61e111197318d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.media3",
          "module": "media3-cast",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-ktor",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-rtmp",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-av1",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-ffmpeg",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-flac",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-iamf",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-midi",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-mpegh",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-opus",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-vp9",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect-lottie",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-effect-ndk",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-workmanager",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector-frame",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose-material3",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-leanback",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils-robolectric",
          "version": {
            "requires": "1.11.0-rc01-dmt"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.11.0-rc01-dmt.aar",
          "url": "media3-common-1.11.0-rc01-dmt.aar",
          "size": 643480,
          "sha512": "a8b73acc52c69ce50a1b8cf05836e2ba5c2199e8ade2dfdc14bd91368cc1cd7b7b6061ff80cee2e0e09dd79b8ffbaee2ec718380bb0bf03d054de18ff059965a",
          "sha256": "2b19297e4dfd101b295ad4c6022c4b257f1bf9560ff6fc23f026824192418fb1",
          "sha1": "8bf30f43e3c07f249e8a52c632a3dbe8f63f05e3",
          "md5": "fcc8a8ee66024c16f0c61e111197318d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-common-1.11.0-rc01-dmt-sources.jar",
          "url": "media3-common-1.11.0-rc01-dmt-sources.jar",
          "size": 525637,
          "sha512": "90231fdfae1e060222ecf15cf70bb64599a430f3c9509120722f4f875061362e1d0d6518f215ae3b5d5cc952f37bdcae18345ff1211bd30582848ed277643239",
          "sha256": "c3a15a470dfbd7586736c8c87aa197d8cec1b5053f790a41046622dcf9ba67ae",
          "sha1": "8ec139f1b24b977a5b0575a12237e8d98efa3c5c",
          "md5": "6d66df8380bfc4b7477c827bcda08cb0"
        }
      ]
    }
  ]
}
